create table customer (
	id bigint generated by default as identity, 
	name varchar(255), 
	tier integer, 
	primary key (id)
);


create table order_product_relationship (
	order_id bigint not null, 
	product_id bigint not null, 
	primary key (order_id, product_id)
);

create table product (
	id bigint generated by default as identity, 
	category varchar(255), 
	name varchar(255), 
	price double, 
	primary key (id)
);

create table product_order (
	id bigint generated by default as identity, 
	order_date date,
	delivery_date date,
	customer_id bigint,
	status varchar(32),
	primary key (id)
);

alter table order_product_relationship add constraint FK_order_product_relationship_product_id_product
foreign key (product_id) references product;

alter table order_product_relationship add constraint FK_order_product_relationship_order_id_product_order
foreign key (order_id) references product_order;

alter table product_order add constraint FK_product_order_customer_id_customer
foreign key (customer_id) references customer;

